<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
        <ContainerRepository>erlizs/spreadsheet-mcp-server</ContainerRepository>
        <ContainerFamily>alpine</ContainerFamily>
        <ContainerUser>root</ContainerUser>
        <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>

        <!-- NuGet dotnet tool -->
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>spreadsheet-mcp-server</ToolCommandName>
        <PackageId>SpreadsheetMcpServer</PackageId>
        <Description>An MCP server for reading and writing Excel/XLSX files via the Model Context Protocol.</Description>
        <Authors>er-ri</Authors>
        <PackageTags>mcp;excel;xlsx;spreadsheet;modelcontextprotocol</PackageTags>
        <RepositoryUrl>https://github.com/er-ri/spreadsheet-mcp-server</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
        <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
        <PackageReference Include="ModelContextProtocol" Version="1.4.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SpreadsheetMcpServer.Core\SpreadsheetMcpServer.Core.csproj" />
    </ItemGroup>
</Project>
